services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host","--port", "1234"]
