_format_version: "2.1"

services:
  - name: api_candidatos
    url: http://api_candidatos:8080 #/v1
    plugins:
      - name: rate-limiting
        config:
          minute: 100
          policy: local
      - name: prometheus
        enabled: true
        config:
          per_consumer: true
          status_code_metrics: true
          latency_metrics: true
          bandwidth_metrics: true
          upstream_health_metrics: true

routes:
  - name: obtener-todos-candidatos
    paths:
      - /api/Candidates/ObtenerTodosCandidatos
    strip_path: false
    service: api_candidatos
    preserve_host: false

  - name: obtener-candidato-por-id
    paths:
      - "/api/Candidates/ObtenerCandidatoPorId"
    strip_path: false
    service: api_candidatos
    preserve_host: false

  - name: obtener-datos-por-nombre-y-apellido
    paths:
      - /api/Candidates/ObtenerDatosPorNombreYApellido
    strip_path: false
    service: api_candidatos
    preserve_host: false

  - name: insertar-nuevo-candidato
    paths:
      - /api/Candidates/InsertarNuevoCandidato
    strip_path: false
    service: api_candidatos
    preserve_host: false

  - name: actualizar-datos-candidato
    paths:
      - /api/Candidates/ActualizarDatosCandidato/
    strip_path: false
    service: api_candidatos
    preserve_host: false

  - name: eliminar-candidato
    paths:
      - /api/Candidates/EliminarCandidato
    strip_path: false
    service: api_candidatos
    preserve_host: false

  - name: obtener-votos-candidato
    paths:
      - /api/Candidates/ObtenerVotosCadidato
    strip_path: false
    service: api_candidatos
    preserve_host: false