name: CI/CD Full Pipeline

on:
  push:
    branches:
      - desarrollo
      - main
      - pruebas-ci-cd
  pull_request:
    branches:
      - desarrollo
      - main
      - pruebas-ci-cd

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 024742722345.dkr.ecr.us-east-1.amazonaws.com
  IMAGE_TAG: latest

jobs:
  # ---------------------------
  # Backend: Linter StyleCop
  # ---------------------------
  backend-linter:
    name: Backend - Ejecutar StyleCop Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependencias npm
        working-directory: Backend
        run: npm install
      - name: Agregar StyleCop.Analyzers
        working-directory: Backend
        run: dotnet add Servicio_1/Api.Candidatos/Api.Candidatos/Api.Candidatos.csproj package StyleCop.Analyzers
      - name: Restaurar paquetes .NET
        working-directory: Backend
        run: dotnet restore Servicio_1/Api.Candidatos/Api.Candidatos/Api.Candidatos.csproj
      - name: Construir proyecto con StyleCop
        working-directory: Backend
        run: dotnet build Servicio_1/Api.Candidatos/Api.Candidatos/Api.Candidatos.csproj /p:RunStyleCop=true

  # ---------------------------
  # Backend: Tests
  # ---------------------------
  backend-test:
    name: Backend - Ejecutar Tests
    runs-on: ubuntu-latest
    needs: backend-linter
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependencias npm
        working-directory: Backend
        run: npm install
      - name: Ejecutar Dotnet Tests para Servicio_1
        working-directory: Backend
        run: npm run test:1

  # ---------------------------
  # Frontend: Linter
  # ---------------------------
  frontend-linter:
    name: Frontend - Ejecutar ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependencias npm
        working-directory: Frontend
        run: npm install
      - name: Ejecutar ESLint
        working-directory: Frontend
        run: npm run lint

  # ---------------------------
  # Frontend: Tests
  # ---------------------------
  frontend-test:
    name: Frontend - Ejecutar Tests
    runs-on: ubuntu-latest
    needs: frontend-linter
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependencias npm
        working-directory: Frontend
        run: npm install
      - name: Ejecutar Vitest
        working-directory: Frontend
        run: npm run test

  # ---------------------------
  # Deploy ECR (Terraform)
  # ---------------------------
  terraform-ecr:
    name: Terraform - Crear ECR
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-test]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Obtener archivo env.tfvars
        run: aws s3 cp s3://gtio-votacion-config/env.tfvars Terraform/env.tfvars

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "latest"

      - name: Terraform Init
        working-directory: Terraform
        run: terraform init

      - name: Terraform Format
        working-directory: Terraform
        run: terraform fmt

      - name: Terraform Validate
        working-directory: Terraform
        run: terraform validate

      - name: Terraform Apply
        working-directory: Terraform
        run: terraform apply -auto-approve -target=module.ecr -var-file=env.tfvars

  # ---------------------------
  # Build y Push de la api
  # ---------------------------
  build-push-api:
    name: Build, Tag y Push imágenes a ECR de la API
    runs-on: ubuntu-latest
    needs: terraform-ecr
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login a ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Instalar Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Crear archivo .env
        run: aws s3 cp s3://gtio-votacion-config/.env .env

      - name: Build imágenes con docker-compose
        run: docker-compose build

      - name: Tag y push imágenes
        run: |
          # Definimos las imágenes locales
          API_CANDIDATOS_IMAGE=gtio_votacion-api
          # API_AUTENTICACION_IMAGE=gtio_votacion-autenticacion

          # Definimos las imágenes en ECR
          ECR_API_CANDIDATOS_IMAGE=gtio_votacion/api
          # ECR_API_AUTENTICACION_IMAGE=gtio_votacion/autenticacion

          # API CANDIDATOS
          docker tag $API_CANDIDATOS_IMAGE ${{ env.ECR_REGISTRY }}/$ECR_API_CANDIDATOS_IMAGE:${{ env.IMAGE_TAG }}
          docker push ${{ env.ECR_REGISTRY }}/$ECR_API_CANDIDATOS_IMAGE:${{ env.IMAGE_TAG }}

          # API AUTENTICACION
        #   docker tag $API_AUTENTICACION_IMAGE ${{ env.ECR_REGISTRY }}/$ECR_API_AUTENTICACION_IMAGE:${{ env.IMAGE_TAG }}
        #   docker push ${{ env.ECR_REGISTRY }}/$ECR_API_AUTENTICACION_IMAGE:${{ env.IMAGE_TAG }}

  terraform-infrastructure-api:
    name: Terraform - Crear infraestructura
    runs-on: ubuntu-latest
    needs: build-push-api
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Crear archivo env.tfvars
        run: aws s3 cp s3://gtio-votacion-config/env.tfvars Terraform/env.tfvars

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "latest"

      - name: Terraform Init
        working-directory: Terraform
        run: echo yes | terraform init -input=false

      - name: Terraform Format
        working-directory: Terraform
        run: terraform fmt

      - name: Terraform Validate
        working-directory: Terraform
        run: terraform validate

      - name: Terraform Apply
        working-directory: Terraform
        run: terraform apply -auto-approve -var-file=env.tfvars -target=module.infraestructure -target=module.api -var-file=env.tfvars

  # ---------------------------
  # Poblar la base de datos
  # ---------------------------
  populate-db:
    name: Poblar base de datos
    runs-on: ubuntu-latest
    needs: terraform-infrastructure-api
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Ejecutar script de poblamiento
        run: curl -X POST http://balanceador-candidatos-666249924.us-east-1.elb.amazonaws.com:8080/api/Candidates/CrearBaseDeDatos

  # ---------------------------
  # Build y Push del frontend
  # ---------------------------
  build-push-frontend:
    name: Build, Tag y Push imágenes a ECR del frontend
    runs-on: ubuntu-latest
    needs: populate-db
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login a ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Instalar Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Crear archivo .env
        run: aws s3 cp s3://gtio-votacion-config/.env .env

      - name: Build imágenes con docker-compose
        run: docker-compose build

      - name: Tag y push imágenes
        run: |
          # Definimos las imágenes locales
          FRONTEND_IMAGE=gtio_votacion-frontend

          # Definimos las imágenes en ECR
          ECR_FRONTEND_IMAGE=gtio_votacion/frontend

          # WEB FRONTEND
          docker tag $FRONTEND_IMAGE ${{ env.ECR_REGISTRY }}/$ECR_FRONTEND_IMAGE:${{ env.IMAGE_TAG }}
          docker push ${{ env.ECR_REGISTRY }}/$ECR_FRONTEND_IMAGE:${{ env.IMAGE_TAG }}