name: Integración Continua

on:
  push:
    branches:
      - ci-testing  # Ejecuta CI en commits a ci-testing
  pull_request:
    branches:
      - ci-testing  # Ejecuta CI en PRs a ci-testing

jobs:
  lint:
    name: Linters Astro, TS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependencias
        working-directory: Frontend
        run: npm install
      - name: Ejecutar ESLint
        working-directory: Frontend
        run: npm run lint

  # test:
  #   name: Ejecutar tests unitarios y de integración
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Instalar dependencias
  #       working-directory: Frontend
  #       run: npm install
  #     - name: Ejecutar jest
  #       working-directory: Frontend
  #       run: npm run test