name: Integración Continua

on:
  push:
    branches:
      - desarrollo # Ejecuta CI en commits a ci-testing
      - main # Ejecuta CI en commits a main
  pull_request:
    branches:
      - desarrollo # Ejecuta CI en PRs a ci-testing
      - main # Ejecuta CI en PRs a main

jobs:
  lint:
    name: Linters Astro, TS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependencias
        working-directory: Frontend
        run: npm install
      - name: Ejecutar ESLint
        working-directory: Frontend
        run: npm run lint

  test:
    name: Ejecutar tests unitarios y de integración
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependencias
        working-directory: Frontend
        run: npm install
      - name: Ejecutar vitest
        working-directory: Frontend
        run: npm run test
